name: Deploy documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: install doc dependencies
          run: |
              sudo apt-get update
              sudo apt-get install -y python3-pip
              sudo pip3 install -r requirements-system.txt
        - name: build docs
          run: |
              cd doc
              make html
        - name: Copy Push Files action
          uses: GuillaumeFalourd/copy-push-files@v1
          with:
          # Files or directories to add separated by space
            source_files: doc/build/html/
          # Commit message
            commit_message: NemesisDroce/Doc CI/CD
          # Branch to push the contents to
            target_branch: main
          # Directory to push the contents to on the new repository
            target_dir: ./
            remote_repository: https://github.com/NemesisDrone/nemesisdrone.github.io
          # Token used to push the code
            access_token: ${{ secrets.TOKEN_GITHUB }}
          
