name: Deploy documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2